Repository colinlienard/gitlight, pull requests merged in 2023-05, with the labels that each got.

#35 feat: improve sidebar
  src/lib/components/common/ShrinkableWrapper.svelte
  src/lib/components/dashboard/Notification.svelte
  src/lib/components/dashboard/sidebar/Sidebar.svelte
  src/lib/components/dashboard/sidebar/SidebarModal.svelte
  src/lib/components/dashboard/sidebar/WatchedRepos.svelte
  src/lib/helpers/createNotificationData.ts
  src/lib/types/common-types.ts
  src/lib/types/github-types.ts
Labels: enhancement, front

#22 fix(back): fix tauri auth
  package.json
  pnpm-lock.yaml
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/Info.plist
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/app.d.ts
  src/routes/+layout.svelte
  src/routes/+layout.ts
Labels: bug, back

#41 feat: add select/deselect all repos
  src/lib/components/dashboard/sidebar/Sidebar.svelte
Labels: feature, front

#44 feat(front): add landing and login pages
  .env.example
  .github/workflows/ci.yml
  .github/workflows/release.yml
  src-tauri/tauri.conf.json
  src/app.html
  src/lib/components/common/Button.svelte
  src/lib/components/common/Tooltip.svelte
  src/lib/components/dashboard/Notification.svelte
  src/lib/components/dashboard/sidebar/Sidebar.svelte
  src/lib/components/index.ts
  src/lib/components/landing/DownloadButton.svelte
  src/lib/components/landing/FakeNotifications.svelte
  src/lib/components/landing/Footer.svelte
  src/lib/components/landing/index.ts
  src/lib/components/settings/LogOutButton.svelte
  src/lib/components/settings/Settings.svelte
  src/lib/icons/Apple.svelte
  src/lib/icons/ArrowRight.svelte
  src/lib/icons/Heart.svelte
  src/lib/icons/Lightning.svelte
  src/lib/icons/Linux.svelte
  src/lib/icons/Sparkles.svelte
  src/lib/icons/Windows.svelte
  src/lib/icons/index.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/dashboard/+page.svelte
  src/routes/login/+page.svelte
  src/styles/_base.scss
  src/styles/_screens.scss
  static/favicon-dark.ico
  static/favicon-light.ico
  static/favicon.png
  static/images/large-light.webp
  static/images/sidebar-gradient.png
  static/images/small-light.webp
  vite.config.ts
Labels: feature, front

#53 feat(front): add download or open app banner
  src/lib/components/dashboard/Banner.svelte
  src/lib/components/dashboard/Main.svelte
  src/lib/components/dashboard/index.ts
  src/lib/components/landing/DownloadButton.svelte
  src/routes/+layout.svelte
  src/routes/+layout.ts
  src/routes/+page.svelte
  src/routes/login/+page.svelte
Labels: enhancement, front

#55 feat: add tauri updater
  .env.example
  .github/workflows/ci.yml
  .github/workflows/release.yml
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
  src/lib/components/landing/DownloadButton.svelte
  src/lib/types/github-types.ts
  src/routes/version/[target]/[version]/+server.ts
Labels: feature, back

#58 feat(front): improve auth from app
  src/routes/+layout.ts
  src/routes/auth/callback/+server.ts
  src/routes/auth/login/+server.ts
  src/routes/login/+page.svelte
Labels: enhancement, feature

#59 fix: wrong notification number in menubar
  src/lib/components/dashboard/Notification.svelte
  src/lib/stores/stores.ts
  src/routes/dashboard/+page.svelte
Labels: bug, front

#60 feat(front): add custom scrollbar
  package.json
  pnpm-lock.yaml
  src/lib/components/common/ScrollbarContainer.svelte
  src/lib/components/common/index.ts
  src/lib/components/dashboard/Main.svelte
  src/lib/components/dashboard/NotificationColumn.svelte
  src/lib/components/dashboard/sidebar/Sidebar.svelte
  src/routes/+layout.ts
Labels: feature, front

#63 fix: deep-link on windows
  package.json
  src/routes/+layout.svelte
Labels: bug, back

#61 feat(front): notifications in vertical
  src/lib/components/common/InlineSelect.svelte
  src/lib/components/common/ScrollbarContainer.svelte
  src/lib/components/common/Separator.svelte
  src/lib/components/common/index.ts
  src/lib/components/dashboard/Main.svelte
  src/lib/components/dashboard/NotificationColumn.svelte
  src/lib/components/dashboard/sidebar/Sidebar.svelte
  src/lib/components/settings/Settings.svelte
  src/lib/stores/stores.ts
  src/lib/types/common-types.ts
  src/routes/dashboard/+page.svelte
Labels: enhancement, front

#65 fix(auth): 404 on login
  package.json
Labels: bug

#71 fix(front): avoid error caused by unsupported notification type
  src/lib/helpers/createNotificationData.ts
Labels: bug, front

#64 feat(front): lighten label's colors
  src/lib/components/common/ScrollbarContainer.svelte
  src/lib/components/dashboard/Notification.svelte
  src/lib/helpers/createNotificationData.ts
  src/lib/helpers/index.ts
  src/lib/helpers/lightenColor.ts
  src/lib/helpers/onScrollVisible.ts
  src/lib/helpers/reactiveFetch.ts
Labels: enhancement, front
