Repository colinlienard/gitlight, pull requests merged in 2023-06, with the labels that each got.

#74 feat(front): cmd+comma to open settings modal
  src/lib/components/common/Modal.svelte
  src/lib/components/settings/Settings.svelte
Labels: enhancement, front

#80 feat(back): store window state after closing the app
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
Labels: feature, back

#81 feat(front): shift-click on repo/group to filter on it
  src/lib/components/dashboard/sidebar/WatchedRepos.svelte
Labels: enhancement, front

#82 feat: launch app at startup
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src/routes/+layout.svelte
Labels: feature, back

#83 feat(settings): add GitHub links
  src/lib/components/settings/Settings.svelte
Labels: feature, front

#89 feat(front): show/hide sidebar
  src/lib/components/dashboard/Main.svelte
  src/lib/components/dashboard/sidebar/Sidebar.svelte
  src/lib/stores/stores.ts
  src/lib/types/common-types.ts
  src/routes/dashboard/+page.svelte
Labels: feature, front

#86 feat(front): support check suite notifications
  src/lib/components/dashboard/NotificationColumn.svelte
  src/lib/helpers/createNotificationData.ts
  src/lib/types/github-types.ts
Labels: feature, front

#90 feat(front): improve settings
  src/lib/components/common/Modal.svelte
  src/lib/components/common/ScrollbarContainer.svelte
  src/lib/components/settings/Accounts.svelte
  src/lib/components/settings/GithubSettings.svelte
  src/lib/components/settings/Preferences.svelte
  src/lib/components/settings/Settings.svelte
  src/lib/components/settings/Update.svelte
  src/lib/stores/stores.ts
Labels: feature, front

#92 perf(front): improve notification animations
  src/lib/components/dashboard/NotificationColumn.svelte
Labels: enhancement, front

#93 feat(front): remove markdown syntax in comments
  src/lib/helpers/createNotificationData.ts
  src/lib/helpers/index.ts
  src/lib/helpers/removeMarkdownSymbols.ts
Labels: feature, front

#94 fix(front): avoid crash when commit author doesn't have avatar
  src/lib/components/dashboard/Notification.svelte
  src/lib/helpers/createNotificationData.ts
  src/lib/types/common-types.ts
  src/lib/types/github-types.ts
Labels: bug, front

#102 feat(front): add basic error handling
  src/lib/components/common/Modal.svelte
  src/lib/components/dashboard/Error.svelte
  src/lib/components/dashboard/index.ts
  src/lib/stores/stores.ts
  src/routes/dashboard/+page.svelte
  src/styles/_mixins.scss
Labels: feature, front

#104 feat(front): add clickable repo and author in notifications
  src/lib/components/dashboard/Notification.svelte
Labels: feature, front

#100 docs: add contributing guide
  CONTRIBUTING.md
  README.md
  assets/dashboard.png
  assets/icon.png
  package.json
Labels: documentation

#107 core: migrate to svelte 4
  package.json
  pnpm-lock.yaml
  src/lib/components/common/Switch.svelte
  src/lib/components/common/Tooltip.svelte
  src/lib/components/dashboard/Notification.svelte
  src/lib/components/settings/LogOutButton.svelte
Labels: front, chore

#109 fix(front): bot detection for merged and closed events
  package.json
  src/lib/helpers/createNotificationData.ts
Labels: bug, front

#106 fix(front): small bugs
  .eslintrc.cjs
  src/lib/components/common/Modal.svelte
  src/lib/components/dashboard/Banner.svelte
  src/lib/components/dashboard/Notification.svelte
  src/lib/components/dashboard/sidebar/Sidebar.svelte
  src/lib/components/dashboard/sidebar/SidebarSection.svelte
  src/lib/components/settings/Settings.svelte
  src/lib/helpers/createNotificationData.ts
  src/lib/helpers/removeMarkdownSymbols.ts
  src/routes/dashboard/+page.svelte
Labels: bug, front

#114 feat(back): update tray icon if new notification appear
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/icons/tray-base.png
  src-tauri/icons/tray-new.png
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/lib/components/dashboard/Main.svelte
  src/lib/components/dashboard/Notification.svelte
  src/routes/dashboard/+page.svelte
Labels: feature, svelte-front, tauri

#117 feat(front): add pr review event
  src/lib/helpers/createNotificationData.ts
  src/lib/types/github-types.ts
Labels: feature, svelte-front
